### ISSUE TITLE
devsite 3 | Events section in Community page

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/atsign.dev-3.0#51]
- [ ] Redesign community page to include an events section, make this section easy to update.

**Comment by Jesseadriano10** [comment]
## Some ideas for the Community page

** The Problem **
- As of right now the community page lacks visuals and needs an event section.

** The Solution **
- Add more Illustrations and implement an Events section on the Community page.

** Alternatives **
- As of right now I do like the way the cards look on the page. Taking Anthony's advice in consideration as to how it would be better if we added more pictures/illustration. We could add a patterned background instead of just placing the cards on whitespace.
- For an events section it would also be a good idea to include a showcase of our most recent articles. This would add more content in case we don't have a lot of events going on at the moment.
- Perhaps adding a sponsors page if we don't have one already

**Additional Context**
https://purpose.nike.com/community - This community page for Nike has a neat community page that includes some of the recent articles.

**Comment by xavierchanth** [comment]
legacy due to #94
